### ISSUE TITLE
Better Printer Support

### ISSUE THREAD

**Issue by lleyton** [tau-OS/ostree#4]
### Problem

Currently, printing in tauOS just doesn't work.

### Proposal

We could ship the Fedora DNF printing group. This would be made easier if rpm-ostree issues [#744](https://github.com/coreos/rpm-ostree/issues/744) and [#2082](https://github.com/coreos/rpm-ostree/issues/2082) are addressed (which we need to do anyway, because syncing the comps with our treefile yaml isn't great.)

**Comment by nothingneko** [comment]
How does Silverblue import the comps?

**Comment by lleyton** [comment]
They don't. They have a sketch python script that generates the yaml files using libcomp.

**Comment by nothingneko** [comment]
> They don't. They have a sketch python script that generates the yaml files using libcomp.
😬
